spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homework-management
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    username: root

  jpa:
    open-in-view: false
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          use_get_generated_keys: true
        dialect: org.hibernate.dialect.MariaDB103Dialect




  data:
    redis:
      host: localhost
      port: 6379
      timeout: 300
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB











#logging:
#  level:
##    root: debug
sa-token:

  #  token??
  token-name: token
  #  token??????
  active-timeout: -1
  #  ??????
  is-concurrent: false
  #  ??????????token
  is-share: true

  #  token??
  token-style: simple-uuid

  #  ??????
  is-log: false
  # jwt??
  jwt-secret-key: shanhai1024




  # redis??
  redis:
    # Redis?????????0?
    database: 1
    # Redis?????
    host: 127.0.0.1
    # Redis???????
    port: 6379
    # Redis?????????????
    # password:
    # ??????
    lettuce:
      pool:
        # ????????
        max-active: 200
        # ???????????????????????
        max-wait: -1ms
        # ???????????
        max-idle: 10
        # ???????????
        min-idle: 0
#debug: true

web:
  upload-path: ./images
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

#又拍云配置

upyun:
  serviceName: graduationdesign
  username: graduationdesign
  password: 31g9pcxG2681ToeQYvYxe7sVfFDijdFe
  filePath: /
#  阿里云配置

aliyun:
  accessKeyId: LTAI5t7U69xcyY67J5c9kG1e
  accessKeySecret: HnOAUsIuYeMNYutIcibq0ZLb1XGq0l
  singName: 阿里云短信测试
  TemplateCode: SMS_154950909

system:
  smsExpireTime: 300